[build]
publish = "public"
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"   
  
[build.environment]
HUGO_VERSION = "0.104.2"
HUGO_ENV = "production"

[[redirects]]
  from = "https://cobalt-docs.netlify.app"
  to = "https://developer.cobalt.io"
  status = 301

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', '*', 'feat/add-algolia']
  mainBranch = 'main'
  disabled = false
  pathPrefix = "/blog"
  customDomain = "cobalt.io"
  renderJavaScript = true
